### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by fredericojordan** [dleitee/crates#1]
Wasn't the `'es,pt'` [option](https://github.com/dleitee/crates/blame/master/readme.md#L49) supposed to generate a `translation.es.json` instead of a `translation.en.json` [file](https://github.com/dleitee/crates/blame/master/readme.md#L59)?
I think there is a minor typo there.

**Comment by dleitee** [comment]
Thanks @fredericojordan .

I fixed that on 4d7ec549
