### ISSUE TITLE
Unable ton install on windows 10

### ISSUE THREAD

**Issue by armaldio** [dleitee/crates#2]
Hello, 

I'm unable ton install this plugin on windows 10

* Using yarn: Installation complete but no binary in .bin
* Using npm: 

```
npm ERR! path XXX\node_modules\crates\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'XXX\node_modules\crates\cli.js'
```

**Comment by dleitee** [comment]
hmm, I'll take a look at that, but I don't have a windows 10 to test it.

Can you help me?

**Comment by dleitee** [comment]
have you tried with docker?

**Comment by armaldio** [comment]
No, I don't know how to setup docker

**Comment by armaldio** [comment]
It "seems" that after making these changes inside the package.json

```diff
   "name": "crates",
   "version": "0.0.10",
   "description": "A tool to generate your locale files compatible with i18n.",
-  "main": "index.js",
+  "main": "src/index.js",
   "bin": {
-    "crates": "cli.js"
+    "crates": "src/cli.js"
   },
```

I'm able to `npm link` and `npm link crates`

**Comment by dleitee** [comment]
Sorry @armaldio, there was a bug and I fixed right now on 666073586939bee

**Comment by dleitee** [comment]
I had published a package with error, sorry.

**Comment by armaldio** [comment]
No problems, I hope this one will fix.
Thanks :D!
